/// Where one of the toolkit's colours comes from: the first of these keys of
/// a Zed `style` that holds a colour.
pub(crate) const COLORS: &[(&str, &[&str])] = &[
    ("foreground", &["text", "editor.foreground"]),
    ("muted.foreground", &["text.muted", "text.placeholder"]),
    ("muted.background", &["surface.background", "element.background"]),
    ("border", &["border", "border.variant"]),
    ("input.border", &["border", "border.variant"]),
    ("window.border", &["border", "border.variant"]),
    ("ring", &["border.focused", "text.accent"]),
    ("primary.background", &["text.accent", "link_text.hover"]),
    ("secondary.background", &["element.background"]),
    ("secondary.hover.background", &["element.hover"]),
    ("secondary.active.background", &["element.active", "element.selected"]),
    ("secondary.foreground", &["text"]),
    ("accent.background", &["element.hover", "ghost_element.hover"]),
    ("accent.foreground", &["text"]),
    ("link", &["link_text.hover", "text.accent"]),
    ("link.hover", &["link_text.hover", "text.accent"]),
    ("link.active", &["link_text.hover", "text.accent"]),
    ("popover.foreground", &["text"]),
    ("list.hover.background", &["ghost_element.hover", "element.hover"]),
    ("list.active.background", &["ghost_element.selected", "element.selected"]),
    ("sidebar.foreground", &["text"]),
    ("sidebar.border", &["border.variant", "border"]),
    ("sidebar.accent.background", &["ghost_element.selected", "element.selected"]),
    ("sidebar.accent.foreground", &["text"]),
    ("sidebar.primary.background", &["text.accent"]),
    ("title_bar.border", &["border.variant", "border"]),
    ("tab.foreground", &["text.muted"]),
    ("tab.active.foreground", &["text"]),
    ("scrollbar.background", &["scrollbar.track.background"]),
    ("scrollbar.thumb.background", &["scrollbar.thumb.background"]),
    ("scrollbar.thumb.hover.background", &["scrollbar.thumb.hover_background"]),
    ("drop_target.background", &["drop_target.background"]),
    ("danger.background", &["error"]),
    ("success.background", &["success"]),
    ("warning.background", &["warning"]),
    ("info.background", &["info"]),
    ("base.red", &["terminal.ansi.red", "error"]),
    ("base.green", &["terminal.ansi.green", "success"]),
    ("base.blue", &["terminal.ansi.blue", "info"]),
    ("base.yellow", &["terminal.ansi.yellow", "warning"]),
    ("base.magenta", &["terminal.ansi.magenta"]),
    ("base.cyan", &["terminal.ansi.cyan"]),
];
